version: '3'

services:
  db:
    image: postgres:15
    platform: linux/amd64
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
     
  web:
    build: .
    platform: linux/amd64
    image: rajshekhorroy/jcvidb_web
    command: >
      sh -c "python /app/jcvidb/manage.py migrate &&
      python /app/jcvidb/manage.py runserver 0.0.0.0:8000 &&
      python /app/jcvidb/manage.py loaddata /app/jcvidb/jcvidb_app/fixtures/initial_data.json"
    volumes:
      # - ./app:/app
#      - /Users/rajshekhorroy/Downloads/ftp:/app/jcvidb/media
      - /home/rajroy/ftp_files:/app/jcvidb/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
volumes:
  postgres_data: