# Generated by Django 4.2.10 on 2024-02-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proteomic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("freeGeneSet", models.CharField(max_length=255)),
                ("createdBy", models.CharField(blank=True, max_length=255, null=True)),
                ("essentiality", models.CharField(max_length=255)),
                (
                    "transporters",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("coverage", models.IntegerField(blank=True, null=True)),
                ("attachment", models.FileField(blank=True, null=True, upload_to="")),
                ("creationDate", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("clearance", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=255)),
                ("lastname", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=255, null=True)),
                ("occupation", models.CharField(max_length=255)),
                ("instituation", models.CharField(max_length=255)),
                ("joined_date", models.DateField(blank=True, null=True)),
                ("role", models.CharField(max_length=255)),
            ],
        ),
    ]
