# Generated by Django 4.2.10 on 2024-02-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jcvidb_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proteomic",
            name="PGAN",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="proteomic",
            name="locusTag",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
