# Generated by Django 4.2.10 on 2024-02-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jcvidb_app", "0002_proteomic_pgan_proteomic_locustag"),
    ]

    operations = [
        migrations.AddField(
            model_name="proteomic",
            name="originalName",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
