# Generated by Django 4.2.10 on 2024-02-19 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jcvidb_app", "0003_proteomic_originalname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="joined_date", new_name="creationDate",
        ),
        migrations.AlterField(
            model_name="proteomic",
            name="createdBy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="jcvidb_app.user"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="jcvidb_app.role"
            ),
        ),
    ]
