# Generated by Django 4.2.10 on 2024-02-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jcvidb_app", "0005_user_approve"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="approve",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
