# Generated by Django 4.2.10 on 2024-02-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jcvidb_app", "0008_alter_proteomic_createdby"),
    ]

    operations = [
        migrations.RemoveField(model_name="proteomic", name="originalName",),
        migrations.AddField(
            model_name="proteomic",
            name="approved",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
