# Generated by Django 4.2.10 on 2024-02-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jcvidb_app", "0009_remove_proteomic_originalname_proteomic_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="proteomic",
            name="upload_code",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
