# Generated by Django 4.2.10 on 2024-02-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jcvidb_app", "0010_proteomic_upload_code"),
    ]

    operations = [
        migrations.RemoveField(model_name="proteomic", name="upload_code",),
        migrations.AddField(
            model_name="proteomic",
            name="originalName",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
