# Generated by Django 4.2.10 on 2024-03-20 01:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jcvidb_app", "0012_data_type_alter_proteomic_creationdate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Basic_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("details", models.TextField(blank=True, null=True)),
                ("references", models.TextField(blank=True, null=True)),
                ("funding", models.TextField(blank=True, null=True)),
                ("approved", models.IntegerField(blank=True, default=0, null=True)),
                ("attachment", models.FileField(blank=True, null=True, upload_to="")),
                (
                    "creationDate",
                    models.DateField(
                        blank=True, default=datetime.date.today, null=True
                    ),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jcvidb_app.user",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jcvidb_app.data_type",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="Proteomic",),
    ]
