# Generated by Django 4.2.10 on 2024-03-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jcvidb_app", "0013_basic_data_delete_proteomic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data_type",
            name="code",
            field=models.CharField(blank=True, default=0, max_length=3, null=True),
        ),
    ]
