# Generated by Django 4.2.10 on 2024-03-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jcvidb_app", "0017_file_data_column_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="column_data",
            name="colun_names",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
