# Generated by Django 4.2.10 on 2024-03-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jcvidb_app", "0018_column_data_colun_names"),
    ]

    operations = [
        migrations.RemoveField(model_name="column_data", name="colun_names",),
        migrations.AddField(
            model_name="column_data",
            name="column_names",
            field=models.TextField(blank=True, default=0, null=True),
        ),
    ]
