# Generated by Django 4.2.10 on 2024-03-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jcvidb_app", "0019_remove_column_data_colun_names_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="basic_data",
            name="code",
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
    ]
